name: Build APK (Docker)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          pwd
          ls -la

      - name: Build APK
        env:
          ANDROIDAPI: "31"
          NDKAPI: "21"
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: tradebot-apk
          path: bin/*.apk
