name: Build APK (native – force stable build-tools)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDAPI: "31"
      NDKAPI: "21"
      ANDROID_BUILD_TOOLS_VERSION: "34.0.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev zlib1g-dev libncurses6 libstdc++6 \
          automake autoconf libtool pkg-config curl
        python -m pip install --upgrade pip wheel
        pip install "cython<3.0" buildozer==1.5.0

    - name: Prime Buildozer (create SDK dirs)
      run: |
        # یک بار اجرا تا فولدرهای buildozer ساخته شود (ممکن است fail شود، مهم نیست)
        buildozer android debug || true

    # === نصب دستی cmdline-tools و سپس نصب پکیج‌های پایدار با sdkmanager ===
    - name: Install Google cmdline-tools + stable SDK packages
      shell: bash
      run: |
        set -e
        SDK="$HOME/.buildozer/android/platform/android-sdk"
        mkdir -p "$SDK/cmdline-tools"
        # دانلود مستقیم cmdline-tools از گوگل و نصب در latest/
        CT_ZIP="$HOME/cmdline-tools.zip"
        curl -L -o "$CT_ZIP" https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        mkdir -p "$SDK/cmdline-tools/latest"
        unzip -qo "$CT_ZIP" -d "$HOME/ctmp"
        # محتویات پوشه tools را به latest کپی کن
        cp -r "$HOME/ctmp/cmdline-tools/"* "$SDK/cmdline-tools/latest/"

        export ANDROID_SDK_ROOT="$SDK"
        export ANDROID_HOME="$SDK"
        TOOLS="$SDK/cmdline-tools/latest/bin"

        yes | "$TOOLS/sdkmanager" --licenses || true
        "$TOOLS/sdkmanager" \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
          || true

        echo "== Installed build-tools =="
        ls -la "$SDK/build-tools" || true

        # اگر هنوز Buildozer بدنبال rc رفت، لینک بده به 34.0.0
        if [ -d "$SDK/build-tools/34.0.0" ] && [ ! -d "$SDK/build-tools/36.1.0-rc1" ]; then
          ln -s "$SDK/build-tools/34.0.0" "$SDK/build-tools/36.1.0-rc1"
        fi

        echo "== PATH sanity =="
        echo "$PATH"
        "$SDK/build-tools/34.0.0/aidl" --version || true

    - name: Build APK (force stable build-tools)
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        ANDROID_HOME: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        ANDROIDAPI: "31"
        NDKAPI: "21"
        ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
      run: |
        # اطمینان از در دسترس بودن ابزارهای build-tools 34.0.0
        export PATH="$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH"
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tradebot-apk
        path: bin/*.apk
