name: Build APK (native)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev zlib1g-dev libncurses6 libstdc++6 \
          automake autoconf libtool pkg-config
        python -m pip install --upgrade pip wheel
        pip install "cython<3.0" buildozer==1.5.0

    - name: Show versions
      run: |
        java -version || true
        python --version
        buildozer --version

    # ---- Build with stable SDK/NDK toolchains and accepted licenses ----
    - name: Build APK (debug)
      env:
        ANDROIDAPI: "31"
        NDKAPI: "21"
      run: |
        # 1) first run to let buildozer fetch SDK/NDK (ignore failure)
        buildozer android debug || true

        # 2) locate Android SDK that buildozer downloaded
        SDK="$HOME/.buildozer/android/platform/android-sdk"

        # 3) ensure cmdline-tools/latest exists to get sdkmanager
        if [ ! -x "$SDK/cmdline-tools/latest/bin/sdkmanager" ]; then
          ALT=$(find "$SDK/cmdline-tools" -maxdepth 1 -type d -name "[0-9]*" | head -n1 || true)
          if [ -n "$ALT" ]; then
            mkdir -p "$SDK/cmdline-tools/latest"
            cp -r "$ALT/." "$SDK/cmdline-tools/latest/"
          fi
        fi

        TOOLS="$SDK/cmdline-tools/latest/bin"

        # 4) accept licenses and install stable packages
        yes | "$TOOLS/sdkmanager" --licenses || true
        "$TOOLS/sdkmanager" "platforms;android-31" "build-tools;34.0.0" || true

        # 5) final build (verbose)
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tradebot-apk
        path: bin/*.apk
