name: Build APK (native)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDAPI: "31"
      NDKAPI: "21"
      ANDROID_BUILD_TOOLS_VERSION: "34.0.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev zlib1g-dev libncurses6 libstdc++6 \
          automake autoconf libtool pkg-config
        python -m pip install --upgrade pip wheel
        pip install "cython<3.0" buildozer==1.5.0

    - name: Prime Buildozer (download SDK/NDK once)
      run: |
        buildozer android debug || true

    - name: Install stable Android SDK + accept licenses
      shell: bash
      run: |
        set -e
        SDK="$HOME/.buildozer/android/platform/android-sdk"

        # ensure sdkmanager exists at .../cmdline-tools/latest/bin
        if [ ! -x "$SDK/cmdline-tools/latest/bin/sdkmanager" ]; then
          ALT=$(find "$SDK/cmdline-tools" -maxdepth 1 -type d -name "[0-9]*" | head -n1 || true)
          if [ -n "$ALT" ]; then
            mkdir -p "$SDK/cmdline-tools/latest"
            cp -r "$ALT/." "$SDK/cmdline-tools/latest/"
          fi
        fi

        export ANDROID_SDK_ROOT="$SDK"
        export ANDROID_HOME="$SDK"
        TOOLS="$SDK/cmdline-tools/latest/bin"

        yes | "$TOOLS/sdkmanager" --licenses || true
        "$TOOLS/sdkmanager" "platform-tools" "platforms;android-31" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "cmdline-tools;latest" || true

        # (اختیاری) اگر Buildozer باز هم دنبال 36.1.0-rc1 رفت، یک symlink از 34.0.0 بساز:
        BT="$SDK/build-tools"
        if [ -d "$BT/34.0.0" ] && [ ! -d "$BT/36.1.0-rc1" ]; then
          ln -s "$BT/34.0.0" "$BT/36.1.0-rc1"
        fi

        ls -la "$SDK/build-tools" || true
        "$TOOLS/sdkmanager" --list | head -n 50 || true

    - name: Build APK (use stable build-tools)
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        ANDROID_HOME: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        ANDROIDAPI: "31"
        NDKAPI: "21"
        ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tradebot-apk
        path: bin/*.apk
