name: Build APK (native – force stable build-tools)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDAPI: "31"
      NDKAPI: "21"
      ANDROID_BUILD_TOOLS_VERSION: "34.0.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev zlib1g-dev libncurses6 libstdc++6 \
          automake autoconf libtool pkg-config
        python -m pip install --upgrade pip wheel
        pip install "cython<3.0" buildozer==1.5.0

    # یک بار اجرا تا SDK/NDK دایرکتوری‌ها ساخته شوند (اگر fail شد مهم نیست)
    - name: Prime Buildozer (fetch SDK/NDK dirs)
      run: |
        buildozer android debug || true

    - name: Install stable SDK & purge rc build-tools
      shell: bash
      run: |
        set -e
        SDK="$HOME/.buildozer/android/platform/android-sdk"

        # ensure sdkmanager is available
        if [ ! -x "$SDK/cmdline-tools/latest/bin/sdkmanager" ]; then
          ALT=$(find "$SDK/cmdline-tools" -maxdepth 1 -type d -name "[0-9]*" | head -n1 || true)
          if [ -n "$ALT" ]; then
            mkdir -p "$SDK/cmdline-tools/latest"
            cp -r "$ALT/." "$SDK/cmdline-tools/latest/"
          fi
        fi

        export ANDROID_SDK_ROOT="$SDK"
        export ANDROID_HOME="$SDK"
        TOOLS="$SDK/cmdline-tools/latest/bin"

        yes | "$TOOLS/sdkmanager" --licenses || true

        # نصب پکیج‌های پایدار
        "$TOOLS/sdkmanager" \
          "platform-tools" \
          "platforms;android-31" \
          "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" \
          "cmdline-tools;latest" || true

        # پاک کردن هر build-tools با rc (پریویو) که باعث ارجاع اشتباه می‌شود
        BT="$SDK/build-tools"
        if [ -d "$BT" ]; then
          find "$BT" -maxdepth 1 -type d -name "rc" -print -exec rm -rf {} \; || true
        fi

        # اگر buildozer هنوز اصرار به 36.1.0-rc1 داشت، به 34.0.0 لینک بده
        if [ -d "$BT/34.0.0" ] && [ ! -d "$BT/36.1.0-rc1" ]; then
          ln -s "$BT/34.0.0" "$BT/36.1.0-rc1"
        fi

        echo "== Installed build-tools =="
        ls -la "$BT" || true
        echo "== sdkmanager list (head) =="
        "$TOOLS/sdkmanager" --list | head -n 80 || true

    - name: Build APK (force stable build-tools)
      env:
        ANDROID_SDK_ROOT: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        ANDROID_HOME: ${{ env.HOME }}/.buildozer/android/platform/android-sdk
        ANDROIDAPI: "31"
        NDKAPI: "21"
        ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
      run: |
        # برای اطمینان، پوشه build-tools/34.0.0 را در PATH می‌گذاریم
        export PATH="$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH"
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tradebot-apk
        path: bin/*.apk
